4-module 3-task
js-tasks-ru/jsbasic-20210420_aleksey-limarev pull request #6
Opened 2021-05-05 06:20 UTC by Aleksey1103

2021-05-05 06:20 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-05-06 14:03 UTC, SinimaWath requested changes

2021-05-06 14:03 UTC, SinimaWath commented on 4-module/3-task/index.js
> +  [...table.tBodies].reduce((a, b) => a.concat([...b.rows]), [])
Тут непонятно, что-такое a и b - нужно назвать подходящими названиями

2021-05-06 14:54 UTC, Aleksey1103 commented on 4-module/3-task/index.js
> +  [...table.tBodies].reduce((a, b) => a.concat([...b.rows]), [])
Спасибо) Поправил

2021-05-06 14:58 UTC, SinimaWath approved these changes

2021-05-06 14:58 UTC, merged